locale:
  default: ru
  use-client-locale: true

commands:
  intercept-ecojobs-root: true

leaderboards:
  cache-seconds: 300
  entries-per-page: 10

boosts:
  stacking: MAX
  cache-millis: 1000
  minimum-multiplier: 1.01
  maximum-multiplier: 10.0
  maximum-duration: 30d
  require-money-placeholder: true

gui:
  items:
    background:
      material: GRAY_STAINED_GLASS_PANE
    back:
      material: BLUE_STAINED_GLASS_PANE
    previous:
      material: BLUE_STAINED_GLASS_PANE
    next:
      material: BLUE_STAINED_GLASS_PANE
    close:
      material: RED_STAINED_GLASS_PANE
    confirm:
      material: GREEN_STAINED_GLASS_PANE
    cancel:
      material: RED_STAINED_GLASS_PANE
    refresh:
      material: REPEATER
    catalog:
      material: CRAFTING_TABLE
